name: Build LLVM

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: "LLVM branch reference to compile (e.g.: release/16.x)"
        required: true
      version:
        description: "Compiled LLVM version number (e.g.: 16)"
        required: true
      configure:
        description: "LLVM enabled projects"
        required: false
        default: clang;mlir;polly

concurrency:
  group: build-llvm-${{ inputs.version }}
  cancel-in-progress: true

env:
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: ${{secrets.CI_STORAGE_USER}}
  storage-token: ${{secrets.CI_STORAGE_TOKEN}}
  storage-path: compilers
  host_jobs: $J

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Env setup
        id: host
        shell: bash
        run: |
          echo "Current host supports ${{env.host_jobs}} parallel jobs"
          echo "jobs=${{env.host_jobs}}" >> $GITHUB_OUTPUT
      - name: Build LLVM ${{inputs.version}}
        id: build
        uses: ./.github/actions/build-llvm
        with:
          jobs: ${{steps.host.outputs.jobs}}
          branch: ${{inputs.git_ref}}
          dist-name: clang+llvm-${{inputs.version}}-bambu
          config-args: ${{ inputs.configure }}
      - name: Upload LLVM ${{inputs.version}} dist directory
        shell: bash
        run: |
          DIST_TAR="${{steps.build.outputs.dist-dir}}.tar.xz"
          STORAGE_URL="${{env.storage-url}}/${{env.storage-path}}/${DIST_TAR}"
          export XZ_OPT='-T0'
          tar -C ${{steps.build.outputs.dist-dir}} . --mode="u+rwX,g+rwX,o+rX" -cJf ${DIST_TAR}
          curl -L --fail -u '${{env.storage-user}}':'${{env.storage-token}}' -T "${DIST_TAR}" "$STORAGE_URL"
          echo "### New release available at https://release.bambuhls.eu/compiler/${DIST_TAR}" >> $GITHUB_STEP_SUMMARY
