name: Merge Pull Request
on:
  pull_request:
    types: [closed]

env:
  storage-url: ${{secrets.CI_STORAGE_URL}}
  storage-user: ${{secrets.CI_STORAGE_USER}}
  storage-token: ${{secrets.CI_STORAGE_TOKEN}}

jobs:
  remove-dist:
    runs-on: [self-hosted]
    steps:
      - name: Remove PR storage directory
        shell: bash
        run: |
          set -e
          PRDIR_URL="${{env.storage-url}}/refs/pull/${{github.event.number}}/"
          AUTH=''
          if [[ ! -z '${{env.storage-user}}' ]]; then
            AUTH='-u ${{env.storage-user}}:${{env.storage-token}} '
          fi
          curl -L --fail -X DELETE $AUTH "$PRDIR_URL"
  update-results:
    if: github.event.pull_request.merged == true && github.base_ref == "main"
    runs-on: [self-hosted]
    steps:
      - name: Update main performance results
        shell: bash
        run: |
          set -e
          PR_URL="${{env.storage-url}}/results/refs/pull/${{github.event.number}}"
          MAIN_URL="${{env.storage-url}}/results/main"
          AUTH=''
          if [[ ! -z '${{env.storage-user}}' ]]; then
            AUTH='-u ${{env.storage-user}}:${{env.storage-token}} '
          fi
          curl -L --fail -X MOVE $AUTH --header "Destination:$MAIN_URL/" "$PR_URL/merge/"
          curl -L --fail -X DELETE $AUTH "$PR_URL/"
